# OK this part
apiVersion: v1
kind: Service
metadata:
  name: mysql
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: sql
spec:
  ports:
    - port: 3306
  selector:
    app: sql
    tier: mysql
  #type: clusterIP Это тип по умолчанию
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlpv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: sql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: sql
spec:
  selector:
    matchLabels:
      app: sql #?
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql
        tier: mysql
    spec:
      containers:
      - image: mysql_img
        name: mysql
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: sqlpv
          mountPath: /var/lib/mysql
      volumes:
      - name: sqlpv
        persistentVolumeClaim:
          claimName: mysql-pv-claim
