FROM alpine:latest
RUN apk update && apk upgrade
RUN apk add bash 

RUN apk add openrc
RUN apk add wget
RUN wget https://dl.grafana.com/oss/release/grafana-7.3.6.linux-amd64.tar.gz
RUN mkdir /grafana
RUN tar -C /grafana -xzvf grafana-7.3.6.linux-amd64.tar.gz --strip-components 1
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
RUN wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-2.32-r0.apk
RUN apk add glibc-2.32-r0.apk
COPY ./grafana.db /grafana/data/
EXPOSE 3000

WORKDIR /grafana/
ENTRYPOINT ["./bin/grafana-server"]

