apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: grafana
spec:
  ports:
    - protocol: TCP
      name: http
      port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: grafana-depl
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: graf_img
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        
      
