apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1 # необязательно
  selector:
    matchLabels:
      app: nginx
  template: # это образец для новых реплик и (может быть) для пересборки
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        #readinessProbe:
        #  failureThreshold: 5
        #  httpGet:
        #    path: /
        #    port: 80
        #  periodSeconds: 10
        #  successThreshold: 2
        #  timeoutSeconds: 3
        #livenessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /
        #    port: 80
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 3
        #  initialDelaySeconds: 10