FROM alpine:latest

RUN apk add bash
RUN apk update && apk upgrade
RUN apk add wget unzip nginx supervisor
RUN apk add php7 php7-fpm php7-json php7-zlib php7-xml php7-pdo php7-phar php7-openssl \
    php7-pdo_mysql php7-mysqli php7-mysqlnd \
    php7-gd php7-mcrypt \
    php7-curl php7-opcache php7-ctype  \
    php7-intl php7-bcmath php7-dom php7-xmlreader --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/testing/
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

COPY ./wp_nginx_cont.sh ./tmp/
RUN chmod +x /tmp/wp_nginx_cont.sh
RUN adduser -D -g 'www' www
COPY ./nginx_conf /etc/nginx/conf.d/default.conf
COPY ./supervisord_conf /etc/supervisord.conf

# wordpress
RUN wget https://ru.wordpress.org/wordpress-5.5-ru_RU.zip
RUN unzip wordpress-5.5-ru_RU.zip
RUN mkdir -p /www1
RUN chown -R www:www /www1
RUN mv wordpress/ /www1
COPY ./wp-config.php /www1/wordpress

EXPOSE 5050

CMD /tmp/wp_nginx_cont.sh
