FROM alpine:latest

RUN apk add bash
RUN apk update && apk upgrade
RUN apk add wget nginx supervisor sudo
RUN apk add php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

COPY ./php_nginx_cont.sh ./tmp/
RUN chmod +x /tmp/php_nginx_cont.sh
RUN adduser -D -g 'www' www

COPY ./nginx_conf /etc/nginx/conf.d/default.conf
COPY ./supervisord_conf /etc/supervisord.conf
 
# phpmyadmin prep
RUN mkdir /www1
RUN chown -R www:www /www1
RUN mkdir -p /www1/phpmyadmin
RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.0.2/phpMyAdmin-5.0.2-all-languages.tar.gz
RUN tar -C /www1/phpmyadmin -xzvf phpMyAdmin-5.0.2-all-languages.tar.gz --strip-components 1
RUN chmod -R 777 /www1/phpmyadmin
COPY ./phpmyadmin.inc.php ./tmp/phpmyadmin.inc.php
RUN mv ./tmp/phpmyadmin.inc.php /www1/phpmyadmin/config.inc.php 
RUN ln -s /www1/phpmyadmin/ /var/www/localhost/htdocs/phpmyadmin

EXPOSE 5000

CMD /tmp/php_nginx_cont.sh
